export const markets = [
  { id: "a", name: "A 股" },
  { id: "hk", name: "港股" },
  { id: "us", name: "美股" },
];

export const stocks = [
  {
    code: "600519",
    name: "贵州茅台",
    market: "a",
    upside: 64,
    sentiment: 72,
    valuation: 58,
    technical: 66,
    samplePrice: 1488,
    history: [
      { label: "1月", price: 1418 },
      { label: "2月", price: 1436 },
      { label: "3月", price: 1452 },
      { label: "4月", price: 1461 },
      { label: "5月", price: 1474 },
      { label: "6月", price: 1488 },
    ],
    historySource: {
      label: "Mock 行情样例",
      frequency: "月度样例",
      updatedAt: "2026-06-01",
    },
    action: "谨慎持有，等待成交量确认后再考虑加仓。",
    reasons: [
      "消费板块情绪回暖，龙头公司更容易获得资金关注。",
      "基本面仍具稳定性，但估值修复空间需要结合业绩增速确认。",
      "技术面短期偏强，若成交量继续放大，趋势确认度会提高。",
    ],
    risks: ["若宏观消费数据弱于预期，短期估值可能继续承压。"],
  },
  {
    code: "0700",
    name: "腾讯控股",
    market: "hk",
    upside: 61,
    sentiment: 69,
    valuation: 63,
    technical: 59,
    samplePrice: 386,
    history: [
      { label: "1月", price: 360 },
      { label: "2月", price: 368 },
      { label: "3月", price: 364 },
      { label: "4月", price: 375 },
      { label: "5月", price: 381 },
      { label: "6月", price: 386 },
    ],
    historySource: {
      label: "Mock 行情样例",
      frequency: "月度样例",
      updatedAt: "2026-06-01",
    },
    action: "适合继续观察，若回调后情绪未转弱，可关注分批机会。",
    reasons: [
      "互联网平台监管预期趋稳，有助于市场重新评估盈利质量。",
      "游戏、广告和金融科技业务改善会影响中期估值弹性。",
      "港股整体流动性仍是关键变量。",
    ],
    risks: ["若港股市场风险偏好下降，股价可能出现较大波动。"],
  },
  {
    code: "AAPL",
    name: "Apple",
    market: "us",
    upside: 57,
    sentiment: 65,
    valuation: 52,
    technical: 61,
    samplePrice: 196,
    history: [
      { label: "1月", price: 184 },
      { label: "2月", price: 181 },
      { label: "3月", price: 188 },
      { label: "4月", price: 190 },
      { label: "5月", price: 193 },
      { label: "6月", price: 196 },
    ],
    historySource: {
      label: "Mock 行情样例",
      frequency: "月度样例",
      updatedAt: "2026-06-01",
    },
    action: "偏向持有观察，等待新品周期和业绩指引进一步确认。",
    reasons: [
      "硬件需求、服务收入和 AI 设备叙事共同影响市场预期。",
      "公司现金流稳健，但估值处于较高区间时需要业绩支撑。",
      "技术面保持韧性，但突破需要新的成交量配合。",
    ],
    risks: ["如果新品需求低于预期，或美股整体估值压缩，短期上涨空间可能受限。"],
  },
];

export const newsByMarket = {
  a: [
    {
      id: "a-001",
      title: "政策继续强调扩大内需，消费与高股息板块受到关注",
      source: "宏观政策",
      importance: 82,
      sentiment: "positive",
      publishedAt: "2026-06-01T00:00:00.000Z",
      relatedTickers: ["600519"],
    },
    {
      id: "a-002",
      title: "部分龙头公司披露回购和分红计划，稳定预期增强",
      source: "公司公告",
      importance: 76,
      sentiment: "positive",
      publishedAt: "2026-06-01T00:00:00.000Z",
      relatedTickers: ["600519"],
    },
  ],
  hk: [
    {
      id: "hk-001",
      title: "南向资金继续流入互联网与高股息资产",
      source: "市场资金",
      importance: 79,
      sentiment: "positive",
      publishedAt: "2026-06-01T00:00:00.000Z",
      relatedTickers: ["0700"],
    },
  ],
  us: [
    {
      id: "us-001",
      title: "大型科技公司继续加码 AI 基础设施投资",
      source: "CEO / 公司动态",
      importance: 81,
      sentiment: "positive",
      publishedAt: "2026-06-01T00:00:00.000Z",
      relatedTickers: ["AAPL"],
    },
  ],
};

export const filings = [
  {
    id: "filing-600519-001",
    market: "a",
    code: "600519",
    title: "贵州茅台披露现金分红与经营质量说明",
    filingType: "公司公告",
    importance: 84,
    publishedAt: "2026-06-01T00:00:00.000Z",
    source: {
      id: "local-fixture-filings",
      label: "Mock 公告样例",
      licenseTag: "sample-fixture-not-official-filing",
      attributionRequired: true,
    },
  },
  {
    id: "filing-0700-001",
    market: "hk",
    code: "0700",
    title: "腾讯控股发布业务更新与回购进展样例",
    filingType: "公司公告",
    importance: 80,
    publishedAt: "2026-06-01T00:00:00.000Z",
    source: {
      id: "local-fixture-filings",
      label: "Mock 公告样例",
      licenseTag: "sample-fixture-not-official-filing",
      attributionRequired: true,
    },
  },
  {
    id: "filing-aapl-001",
    market: "us",
    code: "AAPL",
    title: "Apple 披露资本回报与产品周期风险样例",
    filingType: "公司披露",
    importance: 78,
    publishedAt: "2026-06-01T00:00:00.000Z",
    source: {
      id: "local-fixture-filings",
      label: "Mock 披露样例",
      licenseTag: "sample-fixture-not-official-filing",
      attributionRequired: true,
    },
  },
];

export const publicStatements = [
  {
    id: "statement-a-001",
    market: "a",
    relatedTickers: ["600519"],
    speaker: "监管/政策公开表述样例",
    speakerRole: "政府/监管",
    channel: "公开发布",
    title: "公开表述继续强调扩大内需和稳定市场预期",
    importance: 83,
    sentiment: "positive",
    verified: true,
    publishedAt: "2026-06-01T00:00:00.000Z",
    sourceUrl: "fixture://public-statement/a-001",
  },
  {
    id: "statement-hk-001",
    market: "hk",
    relatedTickers: ["0700"],
    speaker: "公司高管公开表述样例",
    speakerRole: "CEO/高管",
    channel: "公开访谈",
    title: "高管公开表述强调 AI 与游戏业务长期投入",
    importance: 81,
    sentiment: "positive",
    verified: true,
    publishedAt: "2026-06-01T00:00:00.000Z",
    sourceUrl: "fixture://public-statement/hk-001",
  },
  {
    id: "statement-us-001",
    market: "us",
    relatedTickers: ["AAPL"],
    speaker: "CEO 公开表述样例",
    speakerRole: "CEO/高管",
    channel: "公开社交媒体/访谈",
    title: "CEO 公开表述强调 AI 设备体验与隐私保护",
    importance: 82,
    sentiment: "positive",
    verified: true,
    publishedAt: "2026-06-01T00:00:00.000Z",
    sourceUrl: "fixture://public-statement/us-001",
  },
];
